In [54]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import numpy as np

In [55]:
import pandas as pd
from database_handler import execute_query,create_connection,return_data_as_df
from lookups import InputTypes
pd.reset_option('display')

db_session = create_connection()
query = """ SELECT * FROM dw_reporting.dim_gdp_all_measures
 """

df = return_data_as_df(query,InputTypes.SQL,db_session)

C:\Users\user\AppData\Local\Temp\ipykernel_5080\1555817913.py:4: FutureWarning: column_space is deprecated and will be removed in a future version. Use df.to_string(col_space=...) instead.
  pd.reset_option('display')
c:\Users\user\OneDrive\Documents\SE_Factory\FSD\Final_Project\usa_recession_analysis\database_handler.py:64: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return_dataframe = pd.read_sql_query(con= db_session, sql= file_executor)

In [56]:
df

          date        gdp      pce      gpdi    netexp      gcec     impgs
0   2007-01-01  16611.690  28716.4  2664.295  -739.273  3299.115  2317.264
1   2007-04-01  16713.314  29036.2  2699.217  -745.806  3329.139  2368.569
2   2007-07-01  16809.587  29395.1  2685.969  -728.954  3344.222  2414.664
3   2007-10-01  16915.191  29811.4  2642.560  -729.699  3370.950  2480.413
4   2008-01-01  16843.003  30013.4  2563.701  -771.248  3378.654  2584.568
..         ...        ...      ...       ...       ...       ...       ...
61  2022-04-01  21708.160  52245.3  4739.049 -1025.567  3641.161  4069.839
62  2022-07-01  21851.134  53052.6  4724.621  -892.026  3666.982  3976.524
63  2022-10-01  21989.981  53751.2  4796.162  -877.204  3714.800  3891.004
64  2023-01-01  22112.329  54808.7  4725.828  -825.687  3758.768  3890.491
65  2023-04-01  22225.350  55257.0  4780.290  -806.093  3789.786  3767.851

[66 rows x 7 columns]

In [57]:
features = df[['pce', 'gpdi', 'netexp', 'gcec', 'impgs']]
target = df['gdp']

In [58]:
# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

In [59]:
# Initializing the Random Forest Regressor
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)

In [60]:
# Training the model
rf_model.fit(X_train, y_train)

# Making predictions on the test set
predictions = rf_model.predict(X_test)

In [61]:
# Evaluating the model (you can use different metrics based on your requirements)
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')

Mean Squared Error: 25902.730437538758
R-squared: 0.994328553061296

In [62]:
from datetime import datetime, timedelta

# Now, let's predict the GDP for future quarters
# Assuming df is your original DataFrame

# Generating future dates (30 quarters into the future)
future_dates = [df['date'].iloc[-1] + pd.DateOffset(months=i) for i in range(3, 31, 3)]  # Assuming quarterly predictions for the next 30 quarters

In [63]:
future_dates

[Timestamp('2023-07-01 00:00:00'),
 Timestamp('2023-10-01 00:00:00'),
 Timestamp('2024-01-01 00:00:00'),
 Timestamp('2024-04-01 00:00:00'),
 Timestamp('2024-07-01 00:00:00'),
 Timestamp('2024-10-01 00:00:00'),
 Timestamp('2025-01-01 00:00:00'),
 Timestamp('2025-04-01 00:00:00'),
 Timestamp('2025-07-01 00:00:00'),
 Timestamp('2025-10-01 00:00:00')]

In [68]:
future_df = pd.DataFrame(index=future_dates, columns=features.columns)

In [69]:
future_df

            pce gpdi netexp gcec impgs
2023-07-01  NaN  NaN    NaN  NaN   NaN
2023-10-01  NaN  NaN    NaN  NaN   NaN
2024-01-01  NaN  NaN    NaN  NaN   NaN
2024-04-01  NaN  NaN    NaN  NaN   NaN
2024-07-01  NaN  NaN    NaN  NaN   NaN
2024-10-01  NaN  NaN    NaN  NaN   NaN
2025-01-01  NaN  NaN    NaN  NaN   NaN
2025-04-01  NaN  NaN    NaN  NaN   NaN
2025-07-01  NaN  NaN    NaN  NaN   NaN
2025-10-01  NaN  NaN    NaN  NaN   NaN

In [67]:
future_predictions = rf_model.predict(future_df)

c:\Users\user\anaconda3\envs\sefactory_env\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

ValueError: at least one array or dtype is required

In [22]:


# Display the future predictions
future_predictions_df = pd.DataFrame(data={'Future GDP Predictions': future_predictions}, index=future_dates)
future_predictions_df

            Future GDP Predictions
2023-07-01             16493.98729
2023-10-01             16493.98729
2024-01-01             16493.98729
2024-04-01             16493.98729
2024-07-01             16493.98729
2024-10-01             16493.98729
2025-01-01             16493.98729
2025-04-01             16493.98729
2025-07-01             16493.98729
2025-10-01             16493.98729
2026-01-01             16493.98729
2026-04-01             16493.98729
2026-07-01             16493.98729